# Generated by Django 3.1.6 on 2021-04-22 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Forms',
            new_name='ContactForm',
        ),
    ]
