# Generated by Django 3.1.6 on 2021-06-04 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_filesadmin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filesadmin',
            name='title',
        ),
    ]
